### ISSUE TITLE
lsof not available on windows

### ISSUE THREAD

**Issue by dsisnero** [vfreefly/kimurai#4]
In lib/kimurai/capybara/session/driver.rb  line 81 it is trying to call lsof in windows which causes an error

this causes an error in windows

Traceback (most recent call last):
        19: from github.rb:38:in `<main>'
        18: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/base.rb:137:in `start!'
        17: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/base.rb:137:in `each'
        16: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/base.rb:138:in `block in start!'
        15: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/base.rb:179:in `request_to'
        14: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/capybara/session.rb:64:in `visit'
        13: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.6.0/lib/capybara/session.rb:269:in `visit'
        12: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/capybara/session/driver.rb:10:in `driver'
        11: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/capybara/session/driver.rb:50:in `create_session_driver'
        10: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kimurai-0.3.0/lib/kimurai/capybara/session/driver.rb:79:in `get_driver_pid_port'
         9: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.6.0/lib/capybara/selenium/driver.rb:31:in `browser'
         8: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.rb:86:in `for'
         7: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
         6: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
         5: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:42:in `initialize'
         4: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:42:in `new'
         3: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:47:in `initialize'
         2: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:58:in `binary_path'
         1: from c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/platform.rb:127:in `assert_executable'
c:/Dominic/rubies/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/platform.rb:123:in `assert_file': not a file: "/usr/local/b
in/chromedriver" (Selenium::WebDriver::Error::WebDriverError)

**Comment by vfreefly** [comment]
Closed, see https://github.com/vfreefly/kimurai/blob/master/README.md
