### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by patleb** [vfreefly/kimurai#9]
I think you should take a look at github [DMCA](https://help.github.com/articles/dmca-takedown-policy/) guide. In case of wrongdoing relative to this repo (mostly for the question of forks), it might help mitigate some unpleasant surprises, at least it will show good faith on your part.

**Comment by vfreefly** [comment]
Hello @patleb ! Thanks for the link. 
There wasn't any official claim, just a email from a company with a request to delete the code which I did. 

I will reopen the repo soon with a few rewritten parts (readme updated https://github.com/vfreefly/kimurai)

**Comment by patleb** [comment]
:thumbsup:
